### ISSUE TITLE
Move logic to drone-docker instead of duplicating all the code

### ISSUE THREAD

**Issue by fixe** [drone-plugins/drone-ecr#21]
Is this something you guys are willing to accept?

The only thing this PR is doing is getting a password from ECR and executing the same code as `drone-docker` so I think we could remove the code duplication and extend the original plugin.

**Comment by bradrydzewski** [comment]
the approach I'd prefer is to move a subset of the code (everything in [this file](https://github.com/drone-plugins/drone-docker/blob/master/plugin.go)) to a package and then import. We've taken this approach with other plugins as well

**Comment by fixe** [comment]
@bradrydzewski 👍

**Comment by tboerger** [comment]
Yeah, should be cool. Currently we are doing it like that on https://github.com/drone-plugins/drone-git-push

**Comment by bradrydzewski** [comment]
since 0.5 uses environment variables we can retain branded plugins  (ie gcr, ecr) that are simple wrappers are the base docker plugin

### Example

this is how we could wrap the docker plugin for gcr and ecr. We can inherit the docker plugin image, and invoke a wrapper script that can then invoke the plugin:

```
FROM plugins/docker:latest

ENTRYPOINT /bin/wrap-drone-docker.sh 
```

where the `wrap-drone-docker.sh` could do something like this:

``` sh
#!/bin/sh

# map some gcr specific variable names to their docker equivalents
# TODO we should also check for PLUGIN_ equivalents
export DOCKER_USERNAME=_json_key
export DOCKER_PASSWORD=$GCR_TOKEN
export DOCKER_REGISTRY=gcr.io

# invoke the docker plugin
/bin/drone-docker "$@"
```

**Comment by bradrydzewski** [comment]
closing in favor of https://github.com/drone-plugins/drone-ecr/issues/43
